# Minimal dynamic config for local development with SQL visibility.
system.enableReadFromES:
  - value: false
    constraints: {}
system.enableWriteToES:
  - value: false
    constraints: {}
frontend.enableClientVersionCheck:
  - value: true
    constraints: {}
# Reduce partitions for local development to minimize resource usage
matching.numTaskqueueReadPartitions:
  - value: 1
    constraints:
      taskQueueName: "patriot-crawler-tq"
  - value: 1
    constraints:
      taskQueueName: "patriot-scraper-tq"
  - value: 1
    constraints:
      taskQueueName: "patriot-etl-tq"
# Add other task queues here with similar low partition counts if defined 