name: CI

on:
  push:
    branches: ["develop", "feat/**", "bugfix/**"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: patriot_user
          POSTGRES_PASSWORD: patriot_pass
          POSTGRES_DB: patriot_rentals
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U patriot_user -d patriot_rentals" --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm turbo run build
      - name: Typecheck & unit/integration tests
        run: pnpm test
      - name: End-to-end test
        run: pnpm run e2e
        env:
          CI_NO_DOCKER: "true" # Stack already provided by GA services, skip docker-compose
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/